config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  # Static page routes
  get 'pages/index'
  get 'pages/features'
  get 'pages/pricing'
  resources :access_requests, only: %i[new create show]
  root 'pages#index'

  # Address search
  get 'address_search/index'
  resources 'addresses' do
    collection do
      get :states
      get :cities
    end
  end

  #Suburb and Postal_code Suggestions in Advance Search
  resources :suburbs, only: [] do
    collection do
      get :autocomplete      
      get :postal_codes    
    end
  end

  # Agent routes
  devise_for :agents
  resource :agent, only: %i[show edit update] do
    resource :microsoft_graph_session, only: %i[new create destroy], module: :agents

    # A redirect URL called once the Agent has logged in
    resource :microsoft_graph_auth, only: :new, module: :agents
  end
  get '/dashboard', to: 'dashboard#show', as: 'agent_root' # Generate Devise default model path

  # Contact routes
  resources :businesses,  module: :contacts, path: 'contacts/businesses'
  resources :individuals, module: :contacts, path: 'contacts/individuals'
  resources :search_contacts, only: :index, module: :contacts
  resources :contact_search_forms, only: %i[new index], module: :contacts
  resources :contacts, only: %i[index] do
    resources :property_requirements, only: %i[index show create destroy], module: :contacts
    # resources :matching_properties, only: %i[index], module: :contacts
    resources :matching_properties_emails, only: %i[new create], module: :contacts
  end
  
  # Bulk email functionality
  get 'bulk_contact_emails', to: 'contacts/bulk_contact_emails#new', as: 'bulk_contact_emails'
  post 'bulk_contact_emails', to: 'contacts/bulk_contact_emails#create'

  # Property routes
  resources :commercial_properties,  module: :properties, path: 'properties/commercial'
  resources :retail_properties,      module: :properties, path: 'properties/retail'
  resources :industrial_properties,  module: :properties, path: 'properties/industrial'
  resources :residential_properties, module: :properties, path: 'properties/residential'
  resources :archived_properties,    module: :properties, path: 'properties/archived'
  resources :search_properties, only: :index, module: :properties
  resources :property_search_forms, only: %i[new index], module: :properties
  post 'edit_multiple_properties', to: 'properties#edit_multiple'
  resources :properties, only: %i[index show destroy] do
    resource :contract
    resources :property_contacts
    post :contact_filter, to: 'property_contacts#filter'
    resources :listing_enquiries, only: :index, module: :properties
    resources :property_prospects, only: %i[index]
    resources :prospects_properties_emails, only: %i[new create], module: :properties # Email Prospects
    resources :property_activity_logs, only: %i[index]
    resources :images, only: :destroy, module: :properties
    resources :files, only: :destroy, module: :properties
    member do
      patch :unarchive
      resource :share, only: %i[create destroy], module: :properties, as: :share_property # Toggle property sharing
      resource :duplicate_properties, only: :create, module: :properties # Duplicate a property
      resource :griffin_property_com_au_listing, only: %i[new show destroy], module: :properties # GriffinProperty.com.au Listing routes
      resource :rea_listing, only: %i[new show destroy], module: :properties # REA Listing routes
      resource :domain_com_au_listing, only: %i[new show destroy], module: :properties # Domain.com.au Listing routes
    end
  end

  # Property requirements
  namespace :property_requirements do
    resources :search_suburbs, only: :create
  end

  # ListingEnquiries
  resources :listing_enquiries, only: %i[index show destroy] do
    get :read, on: :collection
    get :unread, on: :collection
  end

  # Account mangement
  resource :account, only: %i[edit update] do
    resources :agents, only: %i[index new create edit update], module: :accounts
    resource :microsoft_graph_settings, only: %i[index edit], module: :accounts
    resource :listings, only: %i[edit], module: :accounts
  end

  # Domain.com.au returns a code when accessing the tokens route.
  # See https://developer.domain.com.au/docs/v1/authentication/oauth/authorization-code-grant
  namespace :accounts do
    namespace :domain_com_au do
      resource :access_token, only: :new # Domain.com.au access tokens route
    end
    get ':id/domain_com_au/access_code', to: 'domain_com_au/access_codes#new', as: 'domain_com_au_access_codes'

    # Domain.com.au webhook routes
    get  ':id/domain_com_au/webhooks', to: 'domain_com_au/webhooks#index', as: 'domain_com_au_webhook_verify'
    post ':id/domain_com_au/webhooks', to: 'domain_com_au/webhooks#create', as: 'domain_com_au_webhook'

    # Domain.com.au webhook subscription routes
    delete ':account_id/domain_com_au/webhook_subscriptions/:id', to: 'domain_com_au/webhook_subscriptions#destroy',
                                                                  as: 'delete_domain_com_au_webhook_subscription'
  end

  # Microsoft Graph Auth routes
  match '/auth/:provider/callback', to: 'microsoft/graph/auth#callback', via: %i[get post]

  # Overlord routes
  namespace :console do
    resources :access_requests, only: %i[index show destroy]
    resources :accounts do
      resources :agents
      resources :contacts, except: %i[show create edit update]
      resources :businesses, module: :contacts, only: %i[show create edit update]
      resources :individuals, module: :contacts, only: %i[show create edit update]
      resources :classifiers
      resources :commercial_properties,  module: :properties, path: 'properties/commercial'
      resources :retail_properties,      module: :properties, path: 'properties/retail'
      resources :industrial_properties,  module: :properties, path: 'properties/industrial'
      resources :residential_properties, module: :properties, path: 'properties/residential'
      resources :properties do
        resource :share, only: %i[create destroy], module: :properties, as: :share_property # Toggle property sharing
        resource :contract
        resources :property_contacts
        member do
          get 'real_estate_au'
          resource :rea_listing, only: :show, module: :properties # REA Listing routes
          resource :domain_com_au_listing, only: :show, module: :properties # Domain.com.au Listing routes
        end
      end

      # Property portal webhook routes
      resources :inbound_webhooks, only: %i[index show] do
        get :replay, on: :member
      end
      namespace :domain_com_au do
        resources :webhook_subscriptions, only: %i[index new create show destroy] # , module: :domain_com_au
      end

      # Enquiries
      resources :listing_enquiries, only: %i[index]
      resources :raw_listing_enquiries, only: %i[index]

      # Portal Listings
      resources :portal_listings, only: %i[index show destroy]
    end
    resources :countries do
      resources :states do
        resources :cities
      end
    end
    root 'accounts#index'
  end
  devise_for :overlords

  authenticate :overlord do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :authenticate_agent!
  layout false

  def states
    @country = Country.find_by(slug: params[:country])
    @states = @country.states.all.order(:name).pluck(:name, :id)
    @target = params[:target]
    respond_to do |format|
      format.turbo_stream
    end
  end

  def cities
    @state = State.find(params[:state])
    @cities = @state.cities.all.order(:name).select(:name, :postal_code, :id).collect { |c| ["#{c.name.titleize} (#{c.postal_code})", c.id] }
    @target = params[:target]
    respond_to do |format|
      format.turbo_stream
    end
  end
end

app/controllers/console/access_requests_controller.rb
# frozen_string_literal: true

module Console
  class AccessRequestsController < ConsoleController
    before_action :set_access_request, only: %i[show destroy]

    def index
      @access_requests = AccessRequest.all.order(created_at: :desc)
    end

    def show
    end

    def destroy
      @access_request.destroy
      redirect_to [:console, :access_requests], notice: 'AccessRequest was successfully destroyed.', status: :see_other
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_access_request
      @access_request = AccessRequest.find(params[:id])
    end
  end
end

app/controllers/console/accounts_controller.rb
# frozen_string_literal: true

module Console
  class AccountsController < ConsoleController
    include SortableAttributes

    before_action :set_account, only: %i[show edit update destroy]

    def index
      @accounts = Account.all
      @accounts = @accounts.order(sort_ressource_params) if sort_params?
    end

    def show
    end

    def new
      # @account = Account.new
      @account = CreateAccountForm.new
    end

    def create
      @account = CreateAccountForm.new(CreateAccountForm.permitted_params(params))
      if @account.save
        redirect_to [:console, @account], notice: "#{@account.company_name} was saved."
      else
        # render [:new, :console, @account], alert: 'Cannot save account'
        render :new, status: :unprocessable_entity, alert: 'Cannot save account'
      end
    end

    def edit
    end

    def update
      respond_to do |format|
        if @account.update(account_params)
          format.html { redirect_to [:console, :account], notice: "#{@account.company_name} was successfully updated." }
          format.json { render :show, status: :ok, location: @account }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @account.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @account.destroy
      respond_to do |format|
        format.html { redirect_to [:console, :accounts], notice: "#{@account.company_name} was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    def account_params
      # TODO: Find a better way to drop in ews attributes
      params.require(:account)
            .permit(
              :company_name,
              :domain_name,
              :email,
              :ews_endpoint,
              :ews_synchronize,
              :fax,
              :legal_name,
              :pdf_logo,
              :phone,
              :primary_color,
              :secondary_color,
              :brochure_disclaimer
            )
    end
  end
end

app/controllers/console/addresses_controller.rb
module Console
  class AddressesController < ConsoleController
    before_action :set_address, only: %i[show edit update destroy]

    # GET /addresses or /addresses.json
    def index
      @addresses = Address.all
    end

    # GET /addresses/1 or /addresses/1.json
    def show
    end

    # GET /addresses/new
    def new
      @address = Address.new
    end

    # GET /addresses/1/edit
    def edit
    end

    # POST /addresses or /addresses.json
    def create
      @address = Address.new(address_params)

      respond_to do |format|
        if @address.save
          format.html { redirect_to @address, notice: "Address was successfully created." }
          format.json { render :show, status: :created, location: @address }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @address.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /addresses/1 or /addresses/1.json
    def update
      respond_to do |format|
        if @address.update(address_params)
          format.html { redirect_to @address, notice: "Address was successfully updated." }
          format.json { render :show, status: :ok, location: @address }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @address.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /addresses/1 or /addresses/1.json
    def destroy
      @address.destroy
      respond_to do |format|
        format.html { redirect_to addresses_url, notice: "Address was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def address_params
      params.require(:address).permit(:addressable_type, :addressable_id, :category, :line_1, :line_2, :line_3, :city, :postal_code, :state, :country)
    end
  end
end

app/controllers/console/agents_controller.rb
# frozen_string_literal: true

module Console
  class AgentsController < ConsoleController
    before_action :set_agent, only: %i[show edit update destroy]

    def index
      @agents = @account.agents
                        .order(:last_name, :first_name)
                        .pluck(:first_name, :last_name, :email, :role)
    end

    def show
    end

    def new
      @agent = @account.agents.new
    end

    def create
      @agent = @account.agents.new(agent_params)
      if @agent.save
        redirect_to [:console, @account, @agent], notice: "#{@agent.name} was saved."
      else
        redirect_to [:new, :console, @account, :agent], alert: 'Cannot save agent'
      end
    end

    def edit
    end

    def update
      respond_to do |format|
        if @agent.update(agent_params)
          format.html { redirect_to [:console, @account, @agent], notice: "#{@agent.name} was successfully updated." }
          format.json { render :show, status: :ok, location: @account }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @agent.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @agent.destroy
      respond_to do |format|
        format.html { redirect_to [:console, @account], notice: "#{@agent.name} was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private

    def set_agent
      @agent = @account.agents.find(params[:id])
    end

    def agent_params
      # TODO: Find a better way to drop in ews attributes
      params
        .require(:agent)
        .permit(:account_id, :first_name, :last_name, :email, :password, :password_confirmation, :phone, :mobile, :rea_agent_id)
    end
  end
end

app/controllers/console/cities_controller.rb
# frozen_string_literal: true

module Console
  class CitiesController < ConsoleController
    before_action :set_country
    before_action :set_state
    before_action :set_city, only: %i[show edit update destroy]

    def index
      @cities = @states.cities.all
    end

    def show
    end

    def create
      @country = country.new(params[:country])

      respond_to do |format|
        if @country.save
          format.html { redirect_to console_account_contact_path(@account, @contact), notice: "Contact was successfully updated." }
          format.json { render :show, status: :ok, location: @contact }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @contact.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @country.update
          format.html { redirect_to console_account_contact_path(@account, @contact), notice: "Contact was successfully updated." }
          format.json { render :show, status: :ok, location: @contact }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @contact.errors, status: :unprocessable_entity }
        end
      end
    end

    def edit
    end

    def destroy
      respond_to do |format|
        if @country.destroy
          format.html { redirect_to console_account_contacts_path(@account), notice: "Contact was successfully destroyed." }
          format.json { head :no_content }
        end
      end
    end

    private

    def set_country
      @country = Country.find_by(slug: params[:country_id])
    end

    def set_state
      @state = @country.states.find(params[:state_id])
    end

    def set_city
      @city = @state.cities.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def city_params
      params.require(:city).permit(:state_id, :name, :postal_code, :district_id)
    end
  end
end

app/controllers/console/contacts/businesses_controller.rb
# frozen_string_literal: true

module Console
  module Contacts
    class BusinessesController < Console::ContactsController
      private

      def create_contact_params
        params.require(:business).permit(:type, :agent_id, :account_id, :share, :first_name, :last_name, :individual_name, :legal_name, :job_title, :email, :phone, :mobile, :fax, :url, :registration, :notes, classifications: [], first_address: {}, second_address: {})
      end

      def update_contact_params
        params.require(:business).permit(:type, :agent_id, :account_id, :share, :first_name, :last_name, :individual_name, :legal_name, :job_title, :email, :phone, :mobile, :fax, :url, :registration, :notes, classifications: [], first_address: {}, second_address: {})
      end
    end
  end
end

app/views/console/addresses/_address.html.erb
<%= render Console::ContainerComponent.new do %>
  <%= render CardContainerComponent.new do %>
    <div class="border-t border-gray-200 px-4 py-5 sm:px-6">
      <dl class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-2">
        <% address.attributes.sort.each do |key, value| %>
          <div class="sm:col-span-1">
            <dt class="text-sm font-medium text-gray-500"><%= key %></dt>
            <dd class="mt-1 text-sm text-gray-900"><%= value %></dd>
          </div>
        <% end %>
      </dl>
    </div>
  <% end %>
<% end %>

app/views/console/addresses/_form.html.erb
<%= form_with(model: address) do |form| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
        <% address.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :addressable_type %>
    <%= form.text_field :addressable_type %>
  </div>

  <div class="field">
    <%= form.label :addressable_id %>
    <%= form.number_field :addressable_id %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.number_field :category %>
  </div>

  <div class="field">
    <%= form.label :line_1 %>
    <%= form.text_field :line_1 %>
  </div>

  <div class="field">
    <%= form.label :line_2 %>
    <%= form.text_field :line_2 %>
  </div>

  <div class="field">
    <%= form.label :line_3 %>
    <%= form.text_field :line_3 %>
  </div>

  <div class="field">
    <%= form.label :Suburb %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :postal_code %>
    <%= form.text_field :postal_code %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :country_id %>
    <%= form.text_field :country_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/console/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/console/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Addressable type</th>
      <th>Addressable</th>
      <th>Category</th>
      <th>Line 1</th>
      <th>Line 2</th>
      <th>Line 3</th>
      <th>Suburb</th>
      <th>Postal code</th>
      <th>State</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.addressable_type %></td>
        <td><%= address.addressable_id %></td>
        <td><%= address.category %></td>
        <td><%= address.line_1 %></td>
        <td><%= address.line_2 %></td>
        <td><%= address.line_3 %></td>
        <td><%= address.city %></td>
        <td><%= address.postal_code %></td>
        <td><%= address.state %></td>
        <td><%= address.country_id %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/console/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>

app/views/console/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Addressable type:</strong>
  <%= @address.addressable_type %>
</p>

<p>
  <strong>Addressable:</strong>
  <%= @address.addressable_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @address.category %>
</p>

<p>
  <strong>Line 1:</strong>
  <%= @address.line_1 %>
</p>

<p>
  <strong>Line 2:</strong>
  <%= @address.line_2 %>
</p>

<p>
  <strong>Line 3:</strong>
  <%= @address.line_3 %>
</p>

<p>
  <strong>Suburb:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @address.postal_code %>
</p>

<p>
  <strong>State:</strong>
  <%= @address.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @address.country_id %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>