config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  # Static page routes
  get 'pages/index'
  get 'pages/features'
  get 'pages/pricing'
  resources :access_requests, only: %i[new create show]
  root 'pages#index'

  # Address search
  get 'address_search/index'
  resources 'addresses' do
    collection do
      get :states
      get :cities
    end
  end

  #Suburb and Postal_code Suggestions in Advance Search
  resources :suburbs, only: [] do
    collection do
      get :autocomplete      
      get :postal_codes    
    end
  end

  # Agent routes
  devise_for :agents
  resource :agent, only: %i[show edit update] do
    resource :microsoft_graph_session, only: %i[new create destroy], module: :agents

    # A redirect URL called once the Agent has logged in
    resource :microsoft_graph_auth, only: :new, module: :agents
  end
  get '/dashboard', to: 'dashboard#show', as: 'agent_root' # Generate Devise default model path

  # Contact routes
  resources :businesses,  module: :contacts, path: 'contacts/businesses'
  resources :individuals, module: :contacts, path: 'contacts/individuals'
  resources :search_contacts, only: :index, module: :contacts
  resources :contact_search_forms, only: %i[new index], module: :contacts
  resources :contacts, only: %i[index] do
    resources :property_requirements, only: %i[index show create destroy], module: :contacts
    # resources :matching_properties, only: %i[index], module: :contacts
    resources :matching_properties_emails, only: %i[new create], module: :contacts
  end
  
  # Bulk email functionality
  get 'bulk_contact_emails', to: 'contacts/bulk_contact_emails#new', as: 'bulk_contact_emails'
  post 'bulk_contact_emails', to: 'contacts/bulk_contact_emails#create'

  # Property routes
  resources :commercial_properties,  module: :properties, path: 'properties/commercial'
  resources :retail_properties,      module: :properties, path: 'properties/retail'
  resources :industrial_properties,  module: :properties, path: 'properties/industrial'
  resources :residential_properties, module: :properties, path: 'properties/residential'
  resources :archived_properties,    module: :properties, path: 'properties/archived'
  resources :search_properties, only: :index, module: :properties
  resources :property_search_forms, only: %i[new index], module: :properties
  post 'edit_multiple_properties', to: 'properties#edit_multiple'
  resources :properties, only: %i[index show destroy] do
    resource :contract
    resources :property_contacts
    post :contact_filter, to: 'property_contacts#filter'
    resources :listing_enquiries, only: :index, module: :properties
    resources :property_prospects, only: %i[index]
    resources :prospects_properties_emails, only: %i[new create], module: :properties # Email Prospects
    resources :property_activity_logs, only: %i[index]
    resources :images, only: :destroy, module: :properties
    resources :files, only: :destroy, module: :properties
    member do
      patch :unarchive
      resource :share, only: %i[create destroy], module: :properties, as: :share_property # Toggle property sharing
      resource :duplicate_properties, only: :create, module: :properties # Duplicate a property
      resource :griffin_property_com_au_listing, only: %i[new show destroy], module: :properties # GriffinProperty.com.au Listing routes
      resource :rea_listing, only: %i[new show destroy], module: :properties # REA Listing routes
      resource :domain_com_au_listing, only: %i[new show destroy], module: :properties # Domain.com.au Listing routes
    end
  end

  # Property requirements
  namespace :property_requirements do
    resources :search_suburbs, only: :create
  end

  # ListingEnquiries
  resources :listing_enquiries, only: %i[index show destroy] do
    get :read, on: :collection
    get :unread, on: :collection
  end

  # Account mangement
  resource :account, only: %i[edit update] do
    resources :agents, only: %i[index new create edit update], module: :accounts
    resource :microsoft_graph_settings, only: %i[index edit], module: :accounts
    resource :listings, only: %i[edit], module: :accounts
  end

  # Domain.com.au returns a code when accessing the tokens route.
  # See https://developer.domain.com.au/docs/v1/authentication/oauth/authorization-code-grant
  namespace :accounts do
    namespace :domain_com_au do
      resource :access_token, only: :new # Domain.com.au access tokens route
    end
    get ':id/domain_com_au/access_code', to: 'domain_com_au/access_codes#new', as: 'domain_com_au_access_codes'

    # Domain.com.au webhook routes
    get  ':id/domain_com_au/webhooks', to: 'domain_com_au/webhooks#index', as: 'domain_com_au_webhook_verify'
    post ':id/domain_com_au/webhooks', to: 'domain_com_au/webhooks#create', as: 'domain_com_au_webhook'

    # Domain.com.au webhook subscription routes
    delete ':account_id/domain_com_au/webhook_subscriptions/:id', to: 'domain_com_au/webhook_subscriptions#destroy',
                                                                  as: 'delete_domain_com_au_webhook_subscription'
  end

  # Microsoft Graph Auth routes
  match '/auth/:provider/callback', to: 'microsoft/graph/auth#callback', via: %i[get post]

  # Overlord routes
  namespace :console do
    resources :access_requests, only: %i[index show destroy]
    resources :accounts do
      resources :agents
      resources :contacts, except: %i[show create edit update]
      resources :businesses, module: :contacts, only: %i[show create edit update]
      resources :individuals, module: :contacts, only: %i[show create edit update]
      resources :classifiers
      resources :commercial_properties,  module: :properties, path: 'properties/commercial'
      resources :retail_properties,      module: :properties, path: 'properties/retail'
      resources :industrial_properties,  module: :properties, path: 'properties/industrial'
      resources :residential_properties, module: :properties, path: 'properties/residential'
      resources :properties do
        resource :share, only: %i[create destroy], module: :properties, as: :share_property # Toggle property sharing
        resource :contract
        resources :property_contacts
        member do
          get 'real_estate_au'
          resource :rea_listing, only: :show, module: :properties # REA Listing routes
          resource :domain_com_au_listing, only: :show, module: :properties # Domain.com.au Listing routes
        end
      end

      # Property portal webhook routes
      resources :inbound_webhooks, only: %i[index show] do
        get :replay, on: :member
      end
      namespace :domain_com_au do
        resources :webhook_subscriptions, only: %i[index new create show destroy] # , module: :domain_com_au
      end

      # Enquiries
      resources :listing_enquiries, only: %i[index]
      resources :raw_listing_enquiries, only: %i[index]

      # Portal Listings
      resources :portal_listings, only: %i[index show destroy]
    end
    resources :countries do
      resources :states do
        resources :cities
      end
    end
    root 'accounts#index'
  end
  devise_for :overlords

  authenticate :overlord do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/accounts/agents_controller.rb
# frozen_string_literal: true

module Accounts
  class AgentsController < ApplicationController
    before_action :authenticate_agent!
    before_action :verify_account_manager!
    before_action :set_agent, only: %i[edit update]
    before_action :set_selected_account_menu_option

    def index
      @agents = Current.account.agents.all
    end

    def new
      @agent = Current.account.agents.new
      @agent.build_location
    end

    def create
      @agent = Current.account.agents.new(agent_params)
      @agent.password = SecureRandom.hex(10)
      @agent.password_confirmation = @agent.password

      if @agent.save
        redirect_to [Current.account, :agents], notice: t('.success')
      else
        redirect_to new_account_agent_path(@agent), alert: @agent.errors.full_messages
      end
    end

    def edit
    end

    def update
      if @agent.update(agent_params)
        redirect_to [Current.account, :agents], notice: t('.success')
      else
        redirect_to edit_account_agent_path(@agent), alert: @agent.errors.full_messages
      end
    end

    private

    def agent_params
      params
        .require(:agent)
        .permit(
          :email,
          :first_name,
          :last_name,
          :mobile,
          :phone,
          :role,
          location_attributes: [:id, :time_zone]
        )
    end

    def set_agent
      @agent = Current.account.agents.find(params[:id])
    end

    def set_selected_account_menu_option
      @selected_account_menu_option = :agents
    end
  end
end

app/controllers/agents/microsoft_graph_auths_controller.rb
# frozen_string_literal: true

module Agents
  # Mangages OAuth sign-in for Microsoft Graph
  class MicrosoftGraphAuthsController < ApplicationController
    before_action :authenticate_agent!

    # GET /agent/microsoft_graph_auth/new
    def new
      # Check for errors
      # See https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow
      if error?
        Rails.logger.info params.inspect
        redirect_to edit_agent_path, alert: 'An error occured while trying to login. Please try again.'
      else
        authorization_code = params[:code]
        # Get an access token
        response = authentication_client.exchange_authorization_code_for_access_token(client_id: @account.azure_application_id, tenant_id: @account.azure_tenant_id, client_secret: @account.azure_client_secret, authorization_code: authorization_code, redirect_uri: new_agent_microsoft_graph_auth_url)
        if response.error?
          Rails.logger.info response.body.inspect
          redirect_to edit_agent_path, alert: 'An error occured while trying to get an access token. Please try again.'
        else
          # Save the access token
          Rails.logger.info response.body.inspect
          @current_agent.build_or_update_microsoft_graph_token(response.body)
          redirect_to edit_agent_path, notice: 'Got access token!'
        end
      end
    end

    private

    def error?
      params[:error].present?
    end

    def authentication_client
      @authentication_client ||= Microsoft::Graph::V1::Client.new
    end
  end
end

app/controllers/agents/microsoft_graph_sessions_controller.rb
# frozen_string_literal: true

module Agents
  # Mangages OAuth sign-in for Microsoft Graph
  class MicrosoftGraphSessionsController < ApplicationController
    before_action :authenticate_agent!

    def new
      redirect_to microsoft_graph_url, allow_other_host: true
    end

    private

    def microsoft_graph_url
      Microsoft::Graph::V1::Client.new.authorization_code_grant_url(client_id: client_id, tenant_id: tenant_id, redirect_uri: callback_url)
    end

    def client_id
      @account.azure_application_id
    end

    def tenant_id
      @account.azure_tenant_id
    end

    def callback_url
      new_agent_microsoft_graph_auth_url
    end
  end
end

app/controllers/agents_controller.rb
# frozen_string_literal: true

# No need to set/find @agent since it is
# managed in ApplicationController as
# @current_agent
class AgentsController < ApplicationController
  before_action :authenticate_agent!

  # GET /agent/1 or /agent/1.json
  def show; end

  # GET /agent/1/edit
  def edit
    @current_agent.build_location if @current_agent.location.nil?
  end

  # PATCH/PUT /agent/1 or /agent/1.json
  def update
    if @current_agent.update(agent_params)
      redirect_to edit_agent_path, notice: 'Your information was updated.'
    else
      redirect_to edit_agent_path, alert: @current_agent.errors.full_messages
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def agent_params
    params
      .require(:agent)
      .permit(
        :email,
        :first_name,
        :last_name,
        :phone,
        :mobile,
        :rea_agent_id,
        :domain_com_au_agent_id,
        :fax,
        :ews_username,
        :ews_password,
        addresses_attributes: [:id, :line_1, :line_2, :line_3, :city, :state, :country_id, :account_id],
        location_attributes: [:id, :time_zone]
      )
  end
end

app/controllers/console/access_requests_controller.rb
# frozen_string_literal: true

module Console
  class AccessRequestsController < ConsoleController
    before_action :set_access_request, only: %i[show destroy]

    def index
      @access_requests = AccessRequest.all.order(created_at: :desc)
    end

    def show
    end

    def destroy
      @access_request.destroy
      redirect_to [:console, :access_requests], notice: 'AccessRequest was successfully destroyed.', status: :see_other
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_access_request
      @access_request = AccessRequest.find(params[:id])
    end
  end
end

app/controllers/console/accounts_controller.rb
# frozen_string_literal: true

module Console
  class AccountsController < ConsoleController
    include SortableAttributes

    before_action :set_account, only: %i[show edit update destroy]

    def index
      @accounts = Account.all
      @accounts = @accounts.order(sort_ressource_params) if sort_params?
    end

    def show
    end

    def new
      # @account = Account.new
      @account = CreateAccountForm.new
    end

    def create
      @account = CreateAccountForm.new(CreateAccountForm.permitted_params(params))
      if @account.save
        redirect_to [:console, @account], notice: "#{@account.company_name} was saved."
      else
        # render [:new, :console, @account], alert: 'Cannot save account'
        render :new, status: :unprocessable_entity, alert: 'Cannot save account'
      end
    end

    def edit
    end

    def update
      respond_to do |format|
        if @account.update(account_params)
          format.html { redirect_to [:console, :account], notice: "#{@account.company_name} was successfully updated." }
          format.json { render :show, status: :ok, location: @account }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @account.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @account.destroy
      respond_to do |format|
        format.html { redirect_to [:console, :accounts], notice: "#{@account.company_name} was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    def account_params
      # TODO: Find a better way to drop in ews attributes
      params.require(:account)
            .permit(
              :company_name,
              :domain_name,
              :email,
              :ews_endpoint,
              :ews_synchronize,
              :fax,
              :legal_name,
              :pdf_logo,
              :phone,
              :primary_color,
              :secondary_color,
              :brochure_disclaimer
            )
    end
  end
end

app/controllers/console/addresses_controller.rb
module Console
  class AddressesController < ConsoleController
    before_action :set_address, only: %i[show edit update destroy]

    # GET /addresses or /addresses.json
    def index
      @addresses = Address.all
    end

    # GET /addresses/1 or /addresses/1.json
    def show
    end

    # GET /addresses/new
    def new
      @address = Address.new
    end

    # GET /addresses/1/edit
    def edit
    end

    # POST /addresses or /addresses.json
    def create
      @address = Address.new(address_params)

      respond_to do |format|
        if @address.save
          format.html { redirect_to @address, notice: "Address was successfully created." }
          format.json { render :show, status: :created, location: @address }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @address.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /addresses/1 or /addresses/1.json
    def update
      respond_to do |format|
        if @address.update(address_params)
          format.html { redirect_to @address, notice: "Address was successfully updated." }
          format.json { render :show, status: :ok, location: @address }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @address.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /addresses/1 or /addresses/1.json
    def destroy
      @address.destroy
      respond_to do |format|
        format.html { redirect_to addresses_url, notice: "Address was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def address_params
      params.require(:address).permit(:addressable_type, :addressable_id, :category, :line_1, :line_2, :line_3, :city, :postal_code, :state, :country)
    end
  end
end

app/controllers/console/listing_enquiries_controller.rb
# frozen_string_literal: true

class Console::ListingEnquiriesController < ConsoleController
  def index
    @listing_enquiries = @account.listing_enquiries.all.order(enquired_at: :desc)
  end
end

app/views/console/agents/_agent.html.erb
<p>
  <%= link_to [:console, agent.account, agent] do %>
    <%= agent.name %> (email: <%= agent.email %>)
  <% end %>
</p>

app/views/console/agents/_agents.html.erb
<%= render Console::ContainerComponent.new do %>
  <div class="mt-8 flex flex-col">
    <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
        <div class="relative overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">

          <table class="min-w-full table-fixed divide-y divide-gray-300">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="relative w-12 px-6 sm:w-16 sm:px-8">
                  <input type="checkbox" class="absolute left-4 top-1/2 -mt-2 h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500 sm:left-6">
                </th>
                <th scope="col" class="min-w-[12rem] py-3.5 pr-3 text-left text-sm font-semibold text-gray-900">Name</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Email</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Properties</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Contacts</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Role</th>
                <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                  <span class="sr-only">View</span>
                </th>
              </tr>
            </thead>
            <tbody class="divide-y divide-gray-200 bg-white">
              <% agents.each do |agent| %>
                <!-- Selected: "bg-gray-50" -->
                <tr>
                  <td class="relative w-12 px-6 sm:w-16 sm:px-8">

                    <input type="checkbox" class="absolute left-4 top-1/2 -mt-2 h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500 sm:left-6">
                  </td>
                  <!-- Selected: "text-indigo-600", Not Selected: "text-gray-900" -->
                  <td class="whitespace-nowrap py-4 pr-3 text-sm font-medium text-gray-900">
                    <%= agent.name %>
                  </td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm font-medium text-gray-500">
                    <%= agent.email %>
                  </td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm font-medium text-gray-500">
                    <%= pluralize(agent.properties.size, 'property') %>
                  </td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm font-medium text-gray-500">
                    <%= pluralize(agent.contacts.size, 'contact') %>
                  </td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                    <%= render BadgeComponent.new(text: agent.role.humanize, color: :blue) %>
                  </td>
                  <td class="whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                    <%= link_to console_account_agent_path(@account, agent), class: 'text-indigo-600 hover:text-indigo-900' do %>
                      View<span class="sr-only">, <%= agent.name %></span>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>

        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/console/agents/_form.html.erb
<%= form_with(model: [:console, @account, agent]) do |form| %>
  <% if agent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(agent.errors.count, "error") %> prohibited this agent from being saved:</h2>

      <ul>
        <% agent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :account_id %>
    <%= form.collection_select :account_id, Account.all.order(:company_name), :id, :company_name %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.phone_field :phone %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.phone_field :mobile %>
  </div>

  <div class="field">
    <%= form.label :rea_agent_id %>
    <%= form.text_field :rea_agent_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/console/agents/edit.html.erb
<h1>Edit</h1>

<%= render 'form', agent: @agent %>

<%= link_to 'Back', [:console, @account] %>

app/views/console/agents/index.html.erb
<%= render 'console/shared/account_page_header' %>

<main class="container mx-auto pb-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-base font-semibold leading-6 text-gray-900">Agents</h1>
    </div>
    <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
      <%= link_to 'New agent', new_console_account_agent_path(@account), class: 'block rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600' %>
    </div>
  </div>
  <%= render partial: 'agents', locals: { agents: @account.agents } %>
</main>

app/views/console/agents/new.html.erb
<h1>New Agent</h1>

<%= render 'form', agent: @agent %>

<%= link_to 'Back', [:console, @account] %>

app/views/console/agents/show.html.erb
<%= render 'console/shared/account_page_header' %>

<main class="container mx-auto">
  <%= render CardContainerComponent.new do %>
    <div class="px-4 py-5 sm:px-6 flex justify-between">
      <div>
        <div class="flex flex-row space-x-2">
          <h3 class="text-lg font-medium leading-6 text-gray-900">Agent Information</h3>
          <%= render BadgeComponent.new(text: @agent.role.humanize, color: :blue) %>
        </div>
        <p class="mt-1 max-w-2xl text-sm text-gray-500" title="<%= @agent.created_at %>">Created <%= distance_of_time_in_words_to_now(@account.created_at) %> ago.</p>
      </div>
      <div>
        <%= link_to edit_console_account_agent_path(@account, @agent), class: 'inline-flex items-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2' do %>
          <!-- Heroicon name: mini/pencil -->
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="-ml-1 mr-2 h-5 w-5">
            <path d="M21.731 2.269a2.625 2.625 0 00-3.712 0l-1.157 1.157 3.712 3.712 1.157-1.157a2.625 2.625 0 000-3.712zM19.513 8.199l-3.712-3.712-12.15 12.15a5.25 5.25 0 00-1.32 2.214l-.8 2.685a.75.75 0 00.933.933l2.685-.8a5.25 5.25 0 002.214-1.32L19.513 8.2z" />
          </svg>
          Edit
        <% end %>
      </div>
    </div>
    <div class="border-t border-gray-200 px-4 py-5 sm:px-6">
      <dl class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-2">
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">First name</dt>
          <dd class="mt-1 text-sm text-gray-900"><%= @agent.first_name %></dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">Last name</dt>
          <dd class="mt-1 text-sm text-gray-900"><%= @agent.last_name %></dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">Email address</dt>
          <dd class="mt-1 text-sm text-gray-900"><%= @agent.email %></dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">Phone</dt>
          <dd class="mt-1 text-sm text-gray-900"><%= @agent.phone %></dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">Mobile</dt>
          <dd class="mt-1 text-sm text-gray-900"><%= @agent.mobile %></dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">Fax</dt>
          <dd class="mt-1 text-sm text-gray-900"><%= @agent.fax %></dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">Currently signed in</dt>
          <dd class="mt-1 text-sm text-gray-900"><%= @agent.current_sign_in_at.to_s %></dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">Current IP</dt>
          <dd class="mt-1 text-sm text-gray-900"><%= @agent.current_sign_in_ip %></dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">REA Agent ID</dt>
          <dd class="mt-1 text-sm text-gray-900"><%= @agent.rea_agent_id %></dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">Domain Agent ID</dt>
          <dd class="mt-1 text-sm text-gray-900"><%= @agent.domain_com_au_agent_id %></dd>
        </div>
      </dl>
    </div>
  <% end %>
</main>

<%= render Console::ContainerComponent.new do %>
<% end %>

<p>
  <h2>Contacts</h2>
  <% if @agent.visible_contacts.any? %>
    <%= render partial: 'console/contacts/contacts', locals: { contacts: @agent.visible_contacts } %>
  <% else %>
    <div>
      No contacts yet.
    </div>
  <% end %>
</p>

<p>
  <h2>Properties</h2>
  <% if @agent.properties.any? %>
    <%= render partial: 'console/properties/properties', locals: { properties: @agent.properties } %>
  <% else %>
    <div>
      No properties yet.
    </div>
  <% end %>
  <%= link_to 'Create property', [:new, :console, @account, :property] %>
</p>

<p>
  <h2>Listing Enquiries</h2>
  <% if @agent.listing_enquiries.any? %>
    <%= render partial: 'console/listing_enquiries/listing_enquiries', locals: { listing_enquiries: @agent.listing_enquiries } %>
  <% else %>
    <div>
      No listing enquiries yet.
    </div>
  <% end %>
</p>


<%= link_to 'Edit', [:edit, :console, @agent.account, @agent] %> |
<%= link_to 'Destroy', [:console, @account, @agent], data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %> |
<%= link_to 'Back', console_accounts_path %>