config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  # Static page routes
  get 'pages/index'
  get 'pages/features'
  get 'pages/pricing'
  resources :access_requests, only: %i[new create show]
  root 'pages#index'

  # Address search
  get 'address_search/index'
  resources 'addresses' do
    collection do
      get :states
      get :cities
    end
  end

  #Suburb and Postal_code Suggestions in Advance Search
  resources :suburbs, only: [] do
    collection do
      get :autocomplete      
      get :postal_codes    
    end
  end

  # Agent routes
  devise_for :agents
  resource :agent, only: %i[show edit update] do
    resource :microsoft_graph_session, only: %i[new create destroy], module: :agents

    # A redirect URL called once the Agent has logged in
    resource :microsoft_graph_auth, only: :new, module: :agents
  end
  get '/dashboard', to: 'dashboard#show', as: 'agent_root' # Generate Devise default model path

  # Contact routes
  resources :businesses,  module: :contacts, path: 'contacts/businesses'
  resources :individuals, module: :contacts, path: 'contacts/individuals'
  resources :search_contacts, only: :index, module: :contacts
  resources :contact_search_forms, only: %i[new index], module: :contacts
  resources :contacts, only: %i[index] do
    resources :property_requirements, only: %i[index show create destroy], module: :contacts
    # resources :matching_properties, only: %i[index], module: :contacts
    resources :matching_properties_emails, only: %i[new create], module: :contacts
  end
  
  # Bulk email functionality
  get 'bulk_contact_emails', to: 'contacts/bulk_contact_emails#new', as: 'bulk_contact_emails'
  post 'bulk_contact_emails', to: 'contacts/bulk_contact_emails#create'

  # Property routes
  resources :commercial_properties,  module: :properties, path: 'properties/commercial'
  resources :retail_properties,      module: :properties, path: 'properties/retail'
  resources :industrial_properties,  module: :properties, path: 'properties/industrial'
  resources :residential_properties, module: :properties, path: 'properties/residential'
  resources :archived_properties,    module: :properties, path: 'properties/archived'
  resources :search_properties, only: :index, module: :properties
  resources :property_search_forms, only: %i[new index], module: :properties
  post 'edit_multiple_properties', to: 'properties#edit_multiple'
  resources :properties, only: %i[index show destroy] do
    resource :contract
    resources :property_contacts
    post :contact_filter, to: 'property_contacts#filter'
    resources :listing_enquiries, only: :index, module: :properties
    resources :property_prospects, only: %i[index]
    resources :prospects_properties_emails, only: %i[new create], module: :properties # Email Prospects
    resources :property_activity_logs, only: %i[index]
    resources :images, only: :destroy, module: :properties
    resources :files, only: :destroy, module: :properties
    member do
      patch :unarchive
      resource :share, only: %i[create destroy], module: :properties, as: :share_property # Toggle property sharing
      resource :duplicate_properties, only: :create, module: :properties # Duplicate a property
      resource :griffin_property_com_au_listing, only: %i[new show destroy], module: :properties # GriffinProperty.com.au Listing routes
      resource :rea_listing, only: %i[new show destroy], module: :properties # REA Listing routes
      resource :domain_com_au_listing, only: %i[new show destroy], module: :properties # Domain.com.au Listing routes
    end
  end

  # Property requirements
  namespace :property_requirements do
    resources :search_suburbs, only: :create
  end

  # ListingEnquiries
  resources :listing_enquiries, only: %i[index show destroy] do
    get :read, on: :collection
    get :unread, on: :collection
  end

  # Account mangement
  resource :account, only: %i[edit update] do
    resources :agents, only: %i[index new create edit update], module: :accounts
    resource :microsoft_graph_settings, only: %i[index edit], module: :accounts
    resource :listings, only: %i[edit], module: :accounts
  end

  # Domain.com.au returns a code when accessing the tokens route.
  # See https://developer.domain.com.au/docs/v1/authentication/oauth/authorization-code-grant
  namespace :accounts do
    namespace :domain_com_au do
      resource :access_token, only: :new # Domain.com.au access tokens route
    end
    get ':id/domain_com_au/access_code', to: 'domain_com_au/access_codes#new', as: 'domain_com_au_access_codes'

    # Domain.com.au webhook routes
    get  ':id/domain_com_au/webhooks', to: 'domain_com_au/webhooks#index', as: 'domain_com_au_webhook_verify'
    post ':id/domain_com_au/webhooks', to: 'domain_com_au/webhooks#create', as: 'domain_com_au_webhook'

    # Domain.com.au webhook subscription routes
    delete ':account_id/domain_com_au/webhook_subscriptions/:id', to: 'domain_com_au/webhook_subscriptions#destroy',
                                                                  as: 'delete_domain_com_au_webhook_subscription'
  end

  # Microsoft Graph Auth routes
  match '/auth/:provider/callback', to: 'microsoft/graph/auth#callback', via: %i[get post]

  # Overlord routes
  namespace :console do
    resources :access_requests, only: %i[index show destroy]
    resources :accounts do
      resources :agents
      resources :contacts, except: %i[show create edit update]
      resources :businesses, module: :contacts, only: %i[show create edit update]
      resources :individuals, module: :contacts, only: %i[show create edit update]
      resources :classifiers
      resources :commercial_properties,  module: :properties, path: 'properties/commercial'
      resources :retail_properties,      module: :properties, path: 'properties/retail'
      resources :industrial_properties,  module: :properties, path: 'properties/industrial'
      resources :residential_properties, module: :properties, path: 'properties/residential'
      resources :properties do
        resource :share, only: %i[create destroy], module: :properties, as: :share_property # Toggle property sharing
        resource :contract
        resources :property_contacts
        member do
          get 'real_estate_au'
          resource :rea_listing, only: :show, module: :properties # REA Listing routes
          resource :domain_com_au_listing, only: :show, module: :properties # Domain.com.au Listing routes
        end
      end

      # Property portal webhook routes
      resources :inbound_webhooks, only: %i[index show] do
        get :replay, on: :member
      end
      namespace :domain_com_au do
        resources :webhook_subscriptions, only: %i[index new create show destroy] # , module: :domain_com_au
      end

      # Enquiries
      resources :listing_enquiries, only: %i[index]
      resources :raw_listing_enquiries, only: %i[index]

      # Portal Listings
      resources :portal_listings, only: %i[index show destroy]
    end
    resources :countries do
      resources :states do
        resources :cities
      end
    end
    root 'accounts#index'
  end
  devise_for :overlords

  authenticate :overlord do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/console/contacts/businesses_controller.rb
# frozen_string_literal: true

module Console
  module Contacts
    class BusinessesController < Console::ContactsController
      private

      def create_contact_params
        params.require(:business).permit(:type, :agent_id, :account_id, :share, :first_name, :last_name, :individual_name, :legal_name, :job_title, :email, :phone, :mobile, :fax, :url, :registration, :notes, classifications: [], first_address: {}, second_address: {})
      end

      def update_contact_params
        params.require(:business).permit(:type, :agent_id, :account_id, :share, :first_name, :last_name, :individual_name, :legal_name, :job_title, :email, :phone, :mobile, :fax, :url, :registration, :notes, classifications: [], first_address: {}, second_address: {})
      end
    end
  end
end

app/controllers/console/contacts/individuals_controller.rb
# frozen_string_literal: true

module Console
  module Contacts
    class IndividualsController < Console::ContactsController
      private

      def create_contact_params
        params.require(:business).permit(:type, :agent_id, :account_id, :share, :first_name, :last_name, :individual_name, :legal_name, :job_title, :email, :phone, :mobile, :fax, :url, :registration, :notes, classifications: [], first_address: {}, second_address: {})
      end

      def update_contact_params
        params.require(:business).permit(:type, :agent_id, :account_id, :share, :first_name, :last_name, :individual_name, :legal_name, :job_title, :email, :phone, :mobile, :fax, :url, :registration, :notes, classifications: [], first_address: {}, second_address: {})
      end
    end
  end
end

app/controllers/console/contacts_controller.rb
# frozen_string_literal: true

module Console
  class ContactsController < ConsoleController
    before_action :set_contact, only: %i[show edit update destroy]

    # GET /contacts or /contacts.json
    def index
      @contacts = @account.contacts.all.order(updated_at: :desc)
    end

    # GET /contacts/1 or /contacts/1.json
    def show
    end

    # GET /contacts/new
    def new
      @contact = @account.contacts.new
    end

    # GET /contacts/1/edit
    def edit
    end

    # POST /contacts or /contacts.json
    def create
      @contact = NewContactForm.new(create_contact_params)
      create_contact = ContactServices::CreateContact.new.create_contact(@contact)

      respond_to do |format|
        if create_contact.created?
          format.html { redirect_to console_account_contact_path(@account, create_contact.contact), notice: "Contact was successfully created." }
          format.json { render :show, status: :created, location: @contact }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: create_contact.contact.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /contacts/1 or /contacts/1.json
    def update
      contact = UpdateContactForm.new(update_contact_params)
      update_contact = ContactServices::UpdateContact.new.update_contact(contact, update_contact_params)

      respond_to do |format|
        if update_contact.updated?
          format.html { redirect_to console_account_contact_path(@account, @contact), notice: "Contact was successfully updated." }
          format.json { render :show, status: :ok, location: @contact }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @contact.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /contacts/1 or /contacts/1.json
    def destroy
      @contact.destroy
      respond_to do |format|
        format.html { redirect_to console_account_contacts_path(@account), notice: "Contact was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = @account.contacts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    # def contact_params
    #   params.require(:contact).permit(:type, :agent_id, :account_id, :share, :first_name, :last_name, :business_name, :legal_name, :job_title, :email, :phone, :mobile, :fax, :url, :registration, :notes, classifications: [])
    # end

    # def create_contact_params
    # end

    # def build_update_params
    #   contact_params.merge(contact: @contact)
    # end
  end
end

app/controllers/contacts/contact_search_forms_controller.rb
# frozen_string_literal: true

module Contacts
  class ContactSearchFormsController < ApplicationController
    include Pagy::Backend

    before_action :authenticate_agent!
    before_action :set_nav_menu

    def new
      @contact_search_form = Contacts::ContactSearchForm.new
    end

    def index
      @contact_search_form = Contacts::ContactSearchForm.new(contact_search_form_params)
      @pagy, @contacts = pagy(filtered_contacts)
    end

    private

    def filtered_contacts
      contacts = current_agent.contacts.includes(:agent, :classifications)

      contacts = apply_classification_filter(contacts) if selected_classifications.present?
      contacts = apply_filter_param(contacts) if params[:filter].present?
      contacts = case params[:filter]
                when 'businesses'
                  contacts.order(Arel.sql("COALESCE(business_name, '') ASC"))
                when 'individuals'
                  contacts.order(Arel.sql("COALESCE(first_name, '') ASC"))
                else
                  contacts.order(Arel.sql("COALESCE(first_name, business_name, '') ASC"))
                end

      contacts
    end

    def apply_filter_param(contacts)
      case params[:filter]
      when 'individuals'
        contacts.where(type: 'Individual')
      when 'businesses'
        contacts.where(type: 'Business')
      when '#'
        contacts.where("last_name ~ '^[0-9]' OR business_name ~ '^[0-9]'")
      else
        contacts.where('last_name ILIKE :f OR business_name ILIKE :f', f: "#{params[:filter]}%")
      end
    end

    def apply_classification_filter(contacts)
      normalized = normalize_classifications(selected_classifications)

      contact_ids = Classification.where(classifiable_type: 'Contact').where('LOWER(name) IN (?)', normalized).pluck(:classifiable_id).uniq
    

      contacts.where(id: contact_ids)
    end

    def selected_classifications
      contact_search_form_params[:classifications].presence || []
    end

    def contact_search_form_params
      params.fetch(:contact_search_form, {}).permit(classifications: [])
    end

    def normalize_classifications(names)
      names.map(&:to_s).map(&:strip).map(&:downcase).uniq
    end

    def set_nav_menu
      set_nav_menu_option(:contacts)
    end
  end
end

app/helpers/console/contacts_helper.rb
# frozen_string_literal: true

module Console::ContactsHelper
  def synchronized_with_microsoft_graph_label(contact)
    return nil if contact.nil?

    if !contact.synchronize_with_office_online?
      render BadgeComponent.new(text: 'N/A', color: :gray)
    elsif contact.synchronize_with_office_online?
      render BadgeComponent.new(text: 'Yes', color: :green)
    else
      render BadgeComponent.new(text: 'No', color: :red)
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def contact_index_tabs
    @page_tabs = []
    @page_tabs << PageTabComponent.new(name: 'All', url: contacts_path, active: controller_name == 'contacts' && params[:filter].nil?)
    @page_tabs << PageTabComponent.new(name: 'Individuals', url: individuals_path, active: controller_name == 'individuals')
    @page_tabs << PageTabComponent.new(name: 'Businesses', url: businesses_path, active: controller_name == 'businesses')
    %w(a b c d e f g h i j k l m n o p q r s t u v w x y z #).each do |filter|
      @page_tabs << PageTabComponent.new(name: filter.upcase, url: contacts_path(filter: filter.to_sym), active: params[:filter] == filter)
    end
  end

  def new_individual_button
    content_tag(:span, class: 'block') do
      link_to(new_individual_path, class: 'inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-50 focus:ring-purple-500', role: 'button') do
        concat '<svg xmlns="http://www.w3.org/2000/svg" class="-ml-1 mr-2 h-5 w-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" /></svg>'.html_safe
        concat 'New individual'
      end
    end
  end

  def new_business_button
    content_tag(:span, class: 'block') do
      link_to(new_business_path, class: 'inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-50 focus:ring-purple-500', role: 'button') do
        concat '<svg xmlns="http://www.w3.org/2000/svg" class="-ml-1 mr-2 h-5 w-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" /></svg>'.html_safe
        concat 'New business'
      end
    end
  end

  def edit_contact_button(contact)
    content_tag(:span, class: 'block') do
      link_to [:edit, contact], class: 'inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-50 focus:ring-purple-500', role: 'button' do
        concat '<svg class="-ml-1 mr-2 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true"><path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" /></svg>'.html_safe
        concat 'Edit'
      end
    end
  end

  def contact_shared_by_different_agent?(contact, current_agent)
    contact.agent.id != current_agent.id
  end
end

app/views/contacts/bulk_contact_emails/new.html.erb
<% content_for :page_title do %>
  Send Email to Contacts | Reconnector.app
<% end %>

<%= render Page::HeaderComponent.new('Send Email to Contacts') %>

<div class="bg-yellow-50 border-l-4 border-yellow-400 p-4 mb-6">
  <div class="flex">
    <div class="flex-shrink-0">
      <svg class="h-5 w-5 text-yellow-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
      </svg>
    </div>
    <div class="ml-3">
      <p class="text-sm text-yellow-700">
        <strong>Note:</strong> Email sending will not work on your local machine as your local domain is not registered with Microsoft API. This is for UI and functionality demonstration only.
      </p>
    </div>
  </div>
</div>

<%= render ErrorComponent.new(@bulk_contact_email.errors) if @bulk_contact_email.errors.any? %>

<%= form_with model: @bulk_contact_email, url: bulk_contact_emails_path, local: true, multipart: true do |form| %>
  <div class="space-y-6 w-full">
    <%= render Forms::ContainerComponent.new do %>
      <%= render Forms::SectionComponent.new do %>
        <%= render Forms::GridComponent.new do %>
          <div class="sm:col-span-6">
            <%= form.label :body, class: 'block text-sm font-medium text-gray-700' %>
            <%= form.rich_text_area :body, rows: 8, class: 'mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md' %>
          </div>

          <div class="sm:col-span-6 space-y-4 mb-4">
            <div class="text-base font-medium text-gray-900" aria-hidden="true">Attachments</div>

            <div class="relative flex items-start">
              <div class="flex h-5 items-center">
                <%= form.check_box :attach_brochures, class: 'h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500' %>
              </div>
              <div class="ml-3 text-sm">
                <label for="brochure" class="font-medium text-gray-700">Attach brochures</label>
                <span id="attach-brochure" class="text-gray-500"><span class="sr-only">Attach brochure </span>so that contacts can see the property details offline.</span>
              </div>
            </div>

            <label for="cover-photo" class="block text-sm font-medium text-gray-700">Additional files</label>
            <div class="mt-1 flex justify-center rounded-md border-2 border-dashed border-gray-300 px-6 pt-5 pb-6">
              <div class="space-y-1 text-center">
                <svg class="mx-auto h-12 w-12 text-gray-400" stroke="currentColor" fill="none" viewBox="0 0 48 48" aria-hidden="true">
                  <path d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                </svg>
                <div class="flex text-sm text-gray-600">
                  <%= form.label :files, class: 'relative cursor-pointer rounded-md bg-white font-medium text-indigo-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 hover:text-indigo-500' do %>
                    <span>Upload one or more files</span>
                    <%= form.file_field :files, multiple: true, class: 'sr-only' %>
                  <% end %>
                  <p class="pl-1">or drag and drop</p>
                </div>
                <p class="text-xs text-gray-500">Any files up to 10MB</p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>

      <div class="text-base font-medium text-gray-900" aria-hidden="true">Select the properties</div>
      <%= render Forms::SectionComponent.new do %>
        <div class="relative">
          <!-- Sticky Property requirement section -->
          <div class="z-10 sticky top-0 border-t border-b border-gray-200 bg-gray-50 px-6 py-1 text-sm font-medium text-gray-500">
            Latest 30 properties available for selection
          </div>

          <!-- List of properties -->
          <% if @properties.any? %>
            <%= render partial: 'properties/table', locals: { properties: @properties, sortable: false } %>
          <% else %>
            <div class="flex justify-center py-6">
              <p>No properties found</p>
            </div>
          <% end %>
        </div>
      <% end %>
      
      <!-- Action buttons -->
      <%= render Forms::SectionComponent.new do %>
        <div class="flex justify-end space-x-4 mt-6">
          <%= render ButtonComponent.new(text: 'Back', url: contact_search_forms_path) %>
          <%= render SubmitButtonComponent.new(text: 'Send email', icon: :email) %>
        </div>
      <% end %>

    <% end %>
  <% end %>