config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  # Static page routes
  get 'pages/index'
  get 'pages/features'
  get 'pages/pricing'
  resources :access_requests, only: %i[new create show]
  root 'pages#index'

  # Address search
  get 'address_search/index'
  resources 'addresses' do
    collection do
      get :states
      get :cities
    end
  end

  #Suburb and Postal_code Suggestions in Advance Search
  resources :suburbs, only: [] do
    collection do
      get :autocomplete      
      get :postal_codes    
    end
  end

  # Agent routes
  devise_for :agents
  resource :agent, only: %i[show edit update] do
    resource :microsoft_graph_session, only: %i[new create destroy], module: :agents

    # A redirect URL called once the Agent has logged in
    resource :microsoft_graph_auth, only: :new, module: :agents
  end
  get '/dashboard', to: 'dashboard#show', as: 'agent_root' # Generate Devise default model path

  # Contact routes
  resources :businesses,  module: :contacts, path: 'contacts/businesses'
  resources :individuals, module: :contacts, path: 'contacts/individuals'
  resources :search_contacts, only: :index, module: :contacts
  resources :contact_search_forms, only: %i[new index], module: :contacts
  resources :contacts, only: %i[index] do
    resources :property_requirements, only: %i[index show create destroy], module: :contacts
    # resources :matching_properties, only: %i[index], module: :contacts
    resources :matching_properties_emails, only: %i[new create], module: :contacts
  end
  
  # Bulk email functionality
  get 'bulk_contact_emails', to: 'contacts/bulk_contact_emails#new', as: 'bulk_contact_emails'
  post 'bulk_contact_emails', to: 'contacts/bulk_contact_emails#create'

  # Property routes
  resources :commercial_properties,  module: :properties, path: 'properties/commercial'
  resources :retail_properties,      module: :properties, path: 'properties/retail'
  resources :industrial_properties,  module: :properties, path: 'properties/industrial'
  resources :residential_properties, module: :properties, path: 'properties/residential'
  resources :archived_properties,    module: :properties, path: 'properties/archived'
  resources :search_properties, only: :index, module: :properties
  resources :property_search_forms, only: %i[new index], module: :properties
  post 'edit_multiple_properties', to: 'properties#edit_multiple'
  resources :properties, only: %i[index show destroy] do
    resource :contract
    resources :property_contacts
    post :contact_filter, to: 'property_contacts#filter'
    resources :listing_enquiries, only: :index, module: :properties
    resources :property_prospects, only: %i[index]
    resources :prospects_properties_emails, only: %i[new create], module: :properties # Email Prospects
    resources :property_activity_logs, only: %i[index]
    resources :images, only: :destroy, module: :properties
    resources :files, only: :destroy, module: :properties
    member do
      patch :unarchive
      resource :share, only: %i[create destroy], module: :properties, as: :share_property # Toggle property sharing
      resource :duplicate_properties, only: :create, module: :properties # Duplicate a property
      resource :griffin_property_com_au_listing, only: %i[new show destroy], module: :properties # GriffinProperty.com.au Listing routes
      resource :rea_listing, only: %i[new show destroy], module: :properties # REA Listing routes
      resource :domain_com_au_listing, only: %i[new show destroy], module: :properties # Domain.com.au Listing routes
    end
  end

  # Property requirements
  namespace :property_requirements do
    resources :search_suburbs, only: :create
  end

  # ListingEnquiries
  resources :listing_enquiries, only: %i[index show destroy] do
    get :read, on: :collection
    get :unread, on: :collection
  end

  # Account mangement
  resource :account, only: %i[edit update] do
    resources :agents, only: %i[index new create edit update], module: :accounts
    resource :microsoft_graph_settings, only: %i[index edit], module: :accounts
    resource :listings, only: %i[edit], module: :accounts
  end

  # Domain.com.au returns a code when accessing the tokens route.
  # See https://developer.domain.com.au/docs/v1/authentication/oauth/authorization-code-grant
  namespace :accounts do
    namespace :domain_com_au do
      resource :access_token, only: :new # Domain.com.au access tokens route
    end
    get ':id/domain_com_au/access_code', to: 'domain_com_au/access_codes#new', as: 'domain_com_au_access_codes'

    # Domain.com.au webhook routes
    get  ':id/domain_com_au/webhooks', to: 'domain_com_au/webhooks#index', as: 'domain_com_au_webhook_verify'
    post ':id/domain_com_au/webhooks', to: 'domain_com_au/webhooks#create', as: 'domain_com_au_webhook'

    # Domain.com.au webhook subscription routes
    delete ':account_id/domain_com_au/webhook_subscriptions/:id', to: 'domain_com_au/webhook_subscriptions#destroy',
                                                                  as: 'delete_domain_com_au_webhook_subscription'
  end

  # Microsoft Graph Auth routes
  match '/auth/:provider/callback', to: 'microsoft/graph/auth#callback', via: %i[get post]

  # Overlord routes
  namespace :console do
    resources :access_requests, only: %i[index show destroy]
    resources :accounts do
      resources :agents
      resources :contacts, except: %i[show create edit update]
      resources :businesses, module: :contacts, only: %i[show create edit update]
      resources :individuals, module: :contacts, only: %i[show create edit update]
      resources :classifiers
      resources :commercial_properties,  module: :properties, path: 'properties/commercial'
      resources :retail_properties,      module: :properties, path: 'properties/retail'
      resources :industrial_properties,  module: :properties, path: 'properties/industrial'
      resources :residential_properties, module: :properties, path: 'properties/residential'
      resources :properties do
        resource :share, only: %i[create destroy], module: :properties, as: :share_property # Toggle property sharing
        resource :contract
        resources :property_contacts
        member do
          get 'real_estate_au'
          resource :rea_listing, only: :show, module: :properties # REA Listing routes
          resource :domain_com_au_listing, only: :show, module: :properties # Domain.com.au Listing routes
        end
      end

      # Property portal webhook routes
      resources :inbound_webhooks, only: %i[index show] do
        get :replay, on: :member
      end
      namespace :domain_com_au do
        resources :webhook_subscriptions, only: %i[index new create show destroy] # , module: :domain_com_au
      end

      # Enquiries
      resources :listing_enquiries, only: %i[index]
      resources :raw_listing_enquiries, only: %i[index]

      # Portal Listings
      resources :portal_listings, only: %i[index show destroy]
    end
    resources :countries do
      resources :states do
        resources :cities
      end
    end
    root 'accounts#index'
  end
  devise_for :overlords

  authenticate :overlord do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/account/integrations/domain_com_au.rb
# frozen_string_literal: true

module Account::Integrations::DomainComAu
  extend ActiveSupport::Concern

  included do
    has_many :domain_com_au_listings, through: :properties, source: :domain_com_au_listing
  end
end

app/controllers/accounts/agents_controller.rb
# frozen_string_literal: true

module Accounts
  class AgentsController < ApplicationController
    before_action :authenticate_agent!
    before_action :verify_account_manager!
    before_action :set_agent, only: %i[edit update]
    before_action :set_selected_account_menu_option

    def index
      @agents = Current.account.agents.all
    end

    def new
      @agent = Current.account.agents.new
      @agent.build_location
    end

    def create
      @agent = Current.account.agents.new(agent_params)
      @agent.password = SecureRandom.hex(10)
      @agent.password_confirmation = @agent.password

      if @agent.save
        redirect_to [Current.account, :agents], notice: t('.success')
      else
        redirect_to new_account_agent_path(@agent), alert: @agent.errors.full_messages
      end
    end

    def edit
    end

    def update
      if @agent.update(agent_params)
        redirect_to [Current.account, :agents], notice: t('.success')
      else
        redirect_to edit_account_agent_path(@agent), alert: @agent.errors.full_messages
      end
    end

    private

    def agent_params
      params
        .require(:agent)
        .permit(
          :email,
          :first_name,
          :last_name,
          :mobile,
          :phone,
          :role,
          location_attributes: [:id, :time_zone]
        )
    end

    def set_agent
      @agent = Current.account.agents.find(params[:id])
    end

    def set_selected_account_menu_option
      @selected_account_menu_option = :agents
    end
  end
end

app/controllers/accounts/domain_com_au/access_codes_controller.rb
# frozen_string_literal: true

module Accounts
  module DomainComAu
    # According to https://developer.domain.com.au/docs/latest/authentication/oauth/authorization-code-grant:
    #
    # Once the user has authenticated, the user will be redirected back to the redirect_uri provided in Step 1 along with an authorisation code as part of the redirect url. The new redirect url will look like this
    # {redirect_uri}?code={code}&state={state}
    # redirect_uri: The redirect uri provided in Step 1. This is where your web application will do the exchange of authorisation code to obtain an access token.
    # code: the authorization code to be used next to get an access_token
    # state: the same state value as provided in Step 1
    class AccessCodesController < AuthentificationController
      # GET /accounts/:id/domain_com_au_access_codes/new
      def new
        update_authorization_code = AppServices::DomainComAu::UpdateAuthorizationCode.new.update_authorization_code(authorization_params)

        # TODO: Refactor this ... there has to be a more elegant way to do both operations at once
        get_access_token = AppServices::DomainComAu::GetAccessTokenFromAuthorizationCode.new(account_id: params[:id], redirect_uri: redirect_uri).get_access_token_from_authorization_code
        save_access_token(JSON.parse(get_access_token.body))

        if update_authorization_code.updated?
          redirect_to edit_account_path, notice: 'Authorization code saved.'
        else
          redirect_to edit_account_path, alert: 'Error obtaining an authorization code. Please try again later'
        end
      end

      private

      # Only pass expected params
      def authorization_params
        {
          account_id: params[:id],
          authorization_code: params[:code],
          state: params[:state],
          sessions_state: params[:session_state]
        }
      end

      def save_access_token(access_token_obj)
        @account.domain_com_au_access_token = access_token_obj['access_token']
        @account.domain_com_au_access_token_expires_at = access_token_obj['expires_in'].seconds.from_now
        @account.domain_com_au_access_token_type = access_token_obj['token_type']
        @account.domain_com_au_refresh_token = access_token_obj['refresh_token']
        @account.save(validate: false)
      end
    end
  end
end

app/controllers/accounts/domain_com_au/access_tokens_controller.rb
module Accounts
  module DomainComAu
    class AccessTokensController < AuthentificationController
      # GET /account/domain_com_au_access_token/new
      def new
        @client = DomainComAuServices::V1::Client.new
        redirect_to(
          @client.authorization_code_grant_url(client_id: @account.domain_com_au_client_id, redirect_uri: redirect_uri),
          allow_other_host: true
        )
      end
    end
  end
end

app/controllers/accounts/domain_com_au/authentification_controller.rb
# frozen_string_literal: true

module Accounts
  module DomainComAu
    class AuthentificationController < ApplicationController
      before_action :authenticate_agent!

      private

      def redirect_uri
        accounts_domain_com_au_access_codes_url(@account.id)
      end
    end
  end
end

app/controllers/accounts/domain_com_au/webhook_subscriptions_controller.rb
# frozen_string_literal: true

module Accounts
  module DomainComAu
    class WebhookSubscriptionsController < AuthentificationController
      # DELETE /accounts/:account_id/domain_com_au/webhook_subscriptions/:id(.:format)
      def destroy
        account = Account.find(params[:account_id])
        subscription_id = params[:id]
        response = AppServices::DomainComAu::DeleteWebhookSubscriptions.new(account, subscription_id).delete_webhook_subscription

        if response.success?
          redirect_to edit_account_listings_path, status: :see_other, notice: 'Webhook subscription deleted.'
        else
          redirect_to edit_account_listings_path, status: :see_other, alert: 'Error deleting the webhook subscription. Please try again later'
        end
      end
    end
  end
end

app/controllers/accounts/domain_com_au/webhooks_controller.rb
#frozen_string_literal: true

module Accounts
  module DomainComAu
    # Domain.com.au webhooks controller
    # See https://developer.domain.com.au/docs/latest/apis/pkg_webhooks
    class WebhooksController < ApplicationController
      skip_before_action :verify_authenticity_token
      before_action :set_account

      # See Verification chapter of https://developer.domain.com.au/docs/latest/apis/pkg_webhooks/guides/configuration
      def index
        return head :no_content if valid_verification_code?

        head :not_found
      end

      def create
        # Verify that the webhook is coming from Domain.com.au
        return head :not_found if @account.nil?
        return head :not_found if @account.domain_com_au_webhooks_verification_code.nil?
        return head :not_found if request_signature_missing?
        return head :not_found if signature_does_not_verify?

        # Process the webhook data asynchronously
        WebhookControllerAction.perform_later(@account.id, body)
        head :no_content
      end

      private

      def verification_code
        params['verification']
      end

      def valid_verification_code?
        verification_code.present? &&
          @account.domain_com_au_webhooks_verification_code.present? &&
          verification_code == @account.domain_com_au_webhooks_verification_code
      end

      def set_account
        @account = Account.find(params[:id]) if params[:id].present?
      end

      def signature
        request.headers['X-Domain-Signature']
      end

      def body
        @body ||= request.body.read
      end

      def request_signature_missing?
        signature.blank?
      end

      # Implement the verification of the signature using your secret key
      # https://developer.domain.com.au/docs/latest/apis/pkg_webhooks/guides/processing
      def signature_does_not_verify?
        validation_code = @account.domain_com_au_webhooks_verification_code
        signature != OpenSSL::HMAC.hexdigest('sha1', validation_code, body)
      end

      # Maybe not super clean to put this class here
      # but this job is not an application-wide
      # job but part of the domain...
      class WebhookControllerAction < ApplicationJob
        def perform(account_id, unhashed_params)
          InboundWebhook.create!(account_id: account_id, body: unhashed_params)
        rescue ActiveRecord::RecordInvalid => e
          Rails.logger.error "[#{self.class}] ERROR: Cannot create InboundWebhook with account_id '#{account_id}' and body '#{unhashed_params}'"
          Rails.logger.error e.record.errors
        end
      end
    end
  end
end

app/controllers/accounts/listings_controller.rb
# frozen_string_literal: true

module Accounts
  class ListingsController < ApplicationController
    before_action :authenticate_agent!
    before_action :verify_account_manager!
    before_action :set_selected_account_menu_option

    def edit
      webhook_subscription_service = AppServices::DomainComAu::GetWebhookSubscriptions.new(@account).get_webhook_subscriptions
      @domain_com_au_webhook_subscriptions = webhook_subscription_service.subscriptions
      @account.realestate_com_au_leads_api ||= @account.build_realestate_com_au_leads_api
    end

    private

    def set_selected_account_menu_option
      @selected_account_menu_option = :listings
    end
  end
end

app/controllers/accounts/microsoft_graph_settings_controller.rb
# frozen_string_literal: true

module Accounts
  class MicrosoftGraphSettingsController < ApplicationController
    before_action :authenticate_agent!
    before_action :verify_account_manager!
    before_action :set_selected_account_menu_option

    private

    def set_selected_account_menu_option
      @selected_account_menu_option = :microsoft_graph_settings
    end
  end
end

app/controllers/console/access_requests_controller.rb
# frozen_string_literal: true

module Console
  class AccessRequestsController < ConsoleController
    before_action :set_access_request, only: %i[show destroy]

    def index
      @access_requests = AccessRequest.all.order(created_at: :desc)
    end

    def show
    end

    def destroy
      @access_request.destroy
      redirect_to [:console, :access_requests], notice: 'AccessRequest was successfully destroyed.', status: :see_other
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_access_request
      @access_request = AccessRequest.find(params[:id])
    end
  end
end

app/views/console/accounts/_account.html.erb
<p>
  <strong>Account:</strong>
  <%= link_to account.company_name, [:console, account] %>
</p>

app/views/console/accounts/_form.html.erb
<%= render Console::ContainerComponent.new do %>
  <%= form_with(model: [:console, account]) do |form| %>
    <div class="mt-6 space-y-6">
      <%= render Console::FormSectionComponent.new(header: 'Account information', description: 'General information about the company.') do %>

        <div class="col-span-6 sm:col-span-3">
          <%= render FormLabelComponent.new(form: form, name: :company_name) %>
          <%= render FormTextFieldComponent.new(form: form, name: :company_name, autocomplete: 'company-name') %>
        </div>
        <div class="col-span-6 sm:col-span-3">
          <%= render FormLabelComponent.new(form: form, name: :legal_name) %>
          <%= render FormTextFieldComponent.new(form: form, name: :legal_name, autocomplete: 'legal-name') %>
        </div>
        <div class="col-span-6 sm:col-span-3">
          <%= render FormLabelComponent.new(form: form, name: :domain_name) %>
          <div class="mt-1 flex rounded-md shadow-sm">
            <span class="inline-flex items-center px-3 rounded-l-md border border-r-0 border-gray-300 bg-gray-50 text-gray-500 sm:text-sm">
              https://
            </span>
            <%= render FormTextFieldComponent.new(form: form, name: :domain_name, autocomplete: 'domain-name', class: 'flex-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full min-w-0 rounded-none rounded-r-md sm:text-sm border-gray-300') %>
          </div>
        </div>
        <div class="col-span-6 sm:col-span-3">
          <%= render FormLabelComponent.new(form: form, name: :email) %>
          <%= render FormTextFieldComponent.new(form: form, name: :email, autocomplete: 'email') %>
        </div>
        <div class="col-span-6 sm:col-span-3">
          <%= render FormLabelComponent.new(form: form, name: :phone) %>
          <%= render FormTextFieldComponent.new(form: form, name: :phone, type: :phone, autocomplete: 'phone') %>
        </div>
        <div class="col-span-6 sm:col-span-3">
          <%= render FormLabelComponent.new(form: form, name: :fax) %>
          <%= render FormTextFieldComponent.new(form: form, name: :fax, type: :phone, autocomplete: 'fax') %>
        </div>
        <div class="col-span-6">
          <label for="cover-photo" class="block text-sm font-medium text-gray-700 sm:mt-px sm:pt-2">PDF Brochure logo</label>
          <div class="mt-1 sm:col-span-2 sm:mt-0">
            <div class="flex max-w-lg justify-center rounded-md border-2 border-dashed border-gray-300 px-6 pt-5 pb-6">
              <div class="space-y-1 text-center">
                <svg class="mx-auto h-12 w-12 text-gray-400" stroke="currentColor" fill="none" viewBox="0 0 48 48" aria-hidden="true">
                  <path d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                </svg>
                <div class="flex text-sm text-gray-600">
                  <%= form.label :pdf_logo, class: 'relative cursor-pointer rounded-md bg-white font-medium text-indigo-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 hover:text-indigo-500' do %>
                    <span>Upload a file</span>
                    <%= form.file_field :pdf_logo, multiple: false, direct_upload: true, accept: 'image/svg', class: 'sr-only' %>
                  <% end %>
                  <p class="pl-1">or drag and drop</p>
                </div>
                <p class="text-xs text-gray-500">SVG up to 10MB</p>
              </div>
            </div>
          </div>
        </div>

        <div class="col-span-6 sm:col-span-3">
          <%= render FormLabelComponent.new(form: form, name: :primary_color) %>
          <%= render FormTextFieldComponent.new(form: form, name: :primary_color) %>
        </div>

        <div class="col-span-6 sm:col-span-3">
          <%= render FormLabelComponent.new(form: form, name: :secondary_color) %>
          <%= render FormTextFieldComponent.new(form: form, name: :secondary_color) %>
        </div>

        <div class="col-span-6 sm:col-span-3">
          <%= render FormLabelComponent.new(form: form, name: :brochure_disclaimer) %>
          <%= render FormTextFieldComponent.new(form: form, name: :brochure_disclaimer) %>
        </div>

      <% end %>
      <div class="flex justify-end">
        <%= link_to 'Cancel', console_root_path, class: 'bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' %>
        <%= form.submit class: 'ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/console/accounts/edit.html.erb
<%= render Console::PageHeaderComponent.new(@account.company_name) do |header_component| %>
  <% header_component.with_tabs([
    { title: 'Account', path: console_account_path(@account) },
    { title: 'Agents', path: console_account_agents_path(@account) },
    { title: 'Properties', path: console_account_properties_path(@account) },
    { title: 'Contacts', path: console_account_contacts_path(@account) },
    { title: 'Classifiers', path: console_account_classifiers_path(@account) }
  ]) %>
  <% header_component.with_buttons([
    { title: 'Edit', path: edit_console_account_path(@account) }
  ]) %>
<% end %>

<%= render 'form', account: @account %>

app/views/console/accounts/new.html.erb
<%= render Console::PageHeaderComponent.new('New account') %>

<%= render Console::ContainerComponent.new do %>
  <%= form_with(model: [:console, @account]) do |form| %>
    <div class="mt-6 space-y-6">
      <%= render Console::FormSectionComponent.new(header: 'Account information', description: 'General information about the company.') do %>

        <div class="col-span-6 sm:col-span-3">
          <%= render FormLabelComponent.new(form: form, name: :company_name) %>
          <%= render FormTextFieldComponent.new(form: form, name: :company_name, autocomplete: 'company-name') %>
        </div>
        <div class="col-span-6 sm:col-span-3">
          <%= render FormLabelComponent.new(form: form, name: :legal_name) %>
          <%= render FormTextFieldComponent.new(form: form, name: :legal_name, autocomplete: 'legal-name') %>
        </div>
        <div class="col-span-6 sm:col-span-3">
          <%= render FormLabelComponent.new(form: form, name: :domain_name) %>
          <div class="mt-1 flex rounded-md shadow-sm">
            <span class="inline-flex items-center px-3 rounded-l-md border border-r-0 border-gray-300 bg-gray-50 text-gray-500 sm:text-sm">
              https://
            </span>
            <%= render FormTextFieldComponent.new(form: form, name: :domain_name, autocomplete: 'domain-name', class: 'flex-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full min-w-0 rounded-none rounded-r-md sm:text-sm border-gray-300') %>
          </div>
        </div>
        <div class="col-span-6 sm:col-span-3">
          <%= render FormLabelComponent.new(form: form, name: :email) %>
          <%= render FormTextFieldComponent.new(form: form, name: :email, autocomplete: 'email') %>
        </div>
        <div class="col-span-6 sm:col-span-3">
          <%= render FormLabelComponent.new(form: form, name: :phone) %>
          <%= render FormTextFieldComponent.new(form: form, name: :phone, type: :phone, autocomplete: 'phone') %>
        </div>
        <div class="col-span-6 sm:col-span-3">
          <%= render FormLabelComponent.new(form: form, name: :fax) %>
          <%= render FormTextFieldComponent.new(form: form, name: :fax, type: :phone, autocomplete: 'fax') %>
        </div>

      <% end %>
      <div class="flex justify-end">
        <%= link_to 'Cancel', console_root_path, class: 'bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' %>
        <%= form.submit class: 'ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' %>
      </div>
    </div>
  <% end %>

  <%= form_with(model: [:console, @account]) do |form| %>
    <% if @account.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

        <ul>
          <% @account.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <h2>Account information</h2>

    <div class="field">
      <%= form.label :company_name %>
      <%= form.text_field :company_name %>
    </div>

    <div class="field">
      <%= form.label :legal_name %>
      <%= form.text_field :legal_name %>
    </div>

    <div class="field">
      <%= form.label :domain_name %>
      <%= form.text_field :domain_name %>
    </div>

    <h2>Agent information</h2>

    <div class="field">
      <%= form.label :agent_first_name %>
      <%= form.text_field :agent_first_name %>
    </div>

    <div class="field">
      <%= form.label :agent_last_name %>
      <%= form.text_field :agent_last_name %>
    </div>

    <div class="field">
      <%= form.label :agent_email %>
      <%= form.text_field :agent_email %>
    </div>

    <div class="field">
      <%= form.label :agent_password %>
      <%= form.text_field :agent_password %>
    </div>

    <h2>Address information (Primary)</h2>

    <div class="field">
      <%= form.label :first_address_category %>
      <%= form.text_field :first_address_category %>
    </div>

    <div class="field">
      <%= form.label :first_address_line_1 %>
      <%= form.text_field :first_address_line_1 %>
    </div>

    <div class="field">
      <%= form.label :first_address_line_2 %>
      <%= form.text_field :first_address_line_2 %>
    </div>

    <div class="field">
      <%= form.label :first_address_line_3 %>
      <%= form.text_field :first_address_line_3 %>
    </div>

    <div class="field">
      <%= form.label :first_address_city %>
      <%= form.text_field :first_address_city %>
    </div>

    <div class="field">
      <%= form.label :first_address_postal_code %>
      <%= form.text_field :first_address_postal_code %>
    </div>

    <div class="field">
      <%= form.label :first_address_state %>
      <%= form.text_field :first_address_state %>
    </div>

    <div class="field">
      <%= form.label :first_address_country %>
      <%= form.text_field :first_address_country %>
    </div>

    <h2>Address information (Secondary)</h2>

    <div class="field">
      <%= form.label :second_address_category %>
      <%= form.text_field :second_address_category %>
    </div>

    <div class="field">
      <%= form.label :second_address_line_1 %>
      <%= form.text_field :second_address_line_1 %>
    </div>

    <div class="field">
      <%= form.label :second_address_line_2 %>
      <%= form.text_field :second_address_line_2 %>
    </div>

    <div class="field">
      <%= form.label :second_address_line_3 %>
      <%= form.text_field :second_address_line_3 %>
    </div>

    <div class="field">
      <%= form.label :second_address_city %>
      <%= form.text_field :second_address_city %>
    </div>

    <div class="field">
      <%= form.label :second_address_postal_code %>
      <%= form.text_field :second_address_postal_code %>
    </div>

    <div class="field">
      <%= form.label :second_address_state %>
      <%= form.text_field :second_address_state %>
    </div>

    <div class="field">
      <%= form.label :second_address_country %>
      <%= form.text_field :second_address_country %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

  <%= link_to 'Back', console_accounts_path %>

  <% if Rails.env.development? && @account.errors.any? %>
    <p><%= @account.errors.inspect %></p>
  <% end %>
<% end %>